name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# schedule:
#   - cron: "0 0 * * 0" 


jobs:
  integrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
       
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pip-audit
        run: |
          pip-audit
          
      - name: Format code with black
        run: |
          black . 
          
      - name: Lint Python code
        run: |
          flake8 src/  # Adjust the path based on your source code location
        

      - name: Set PYTHONPATH
        run: |
          export PYTHONPATH=$(pwd)
          echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
          
      - name: Run Python tests
        run: |
          PYTHONPATH=$(pwd) pytest tests/ --maxfail=1 --disable-warnings

      - name: Build Docker image
        run: |
         docker build -t my_flask_app .
         
      - name: Run Docker containter
        run: |
         docker run -d -p 5000:5000 my_flask_app

          
      - name: Test Hello World
        run: |
          sleep 5  # Wait for the app to start
          curl -f http://localhost:5000 || exit 1  # Fail if the app doesn't respond
            
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
          
      - name: Tag and push Docker image
        run: |
          docker tag my_flask_app ${{ secrets.DOCKER_USERNAME }}/my_flask_app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my_flask_app:latest       


  deploy:
    runs-on: ubuntu-latest
    needs: integrate  # Ensure the integrate job completes successfully
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      
      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/my_flask_app:latest

      - name: Deploy (replace this with your actual deployment command)
        run: echo "Deploying my_flask_app"